services:
  runners-hi-backend:
    image: hanol98/runners-hi-backend:latest
    #    build: .
    container_name: runners-hi-backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true # 외부 네트워크 사용