services:
  backend:
    image: runners-hi-backend:latest
    container_name: backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true # 외부 네트워크 사용