-- 1. MEMBER TABLE
CREATE TABLE MEMBER
(
    MEMBER_ID    NUMBER PRIMARY KEY,
    EMAIL        VARCHAR2(255) NOT NULL,
    NICKNAME     VARCHAR2(255) NOT NULL,
    USERNAME     VARCHAR2(255) NOT NULL,
    PWD_HASH     VARCHAR2(255) NOT NULL,
    ROLE         VARCHAR2(50) DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN') ),
    PROFILE_PATH VARCHAR2(500),
    CREATED_AT   TIMESTAMP    DEFAULT SYSDATE,
--     CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    DELETED_AT   TIMESTAMP,
    DELETED_BY   NUMBER
);
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1;

-- 2. CREW TABLE
CREATE TABLE CREW
(
    CREW_ID      NUMBER PRIMARY KEY,
    CREW_NAME    VARCHAR2(255) NOT NULL,
    CREW_ADDRESS VARCHAR2(255) NOT NULL,
    CREW_REGION  VARCHAR2(100) NOT NULL,
    INTRODUCE    VARCHAR2(1000),
    PROFILE_PATH VARCHAR2(500),
    CREATED_AT   TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW START WITH 1 INCREMENT BY 1;

-- 3. CREW_MEMBER TABLE
CREATE TABLE CREW_MEMBER
(
    CREW_MEMBER_ID NUMBER PRIMARY KEY,
    MEMBER_ID      NUMBER REFERENCES MEMBER (MEMBER_ID),
    CREW_ID        NUMBER REFERENCES CREW (CREW_ID),
    IS_LEADER      CHAR(1)   DEFAULT 'N' CHECK ( IS_LEADER IN ('Y', 'N') ),
    CREATED_AT     TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY     NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW_MEMBER START WITH 1 INCREMENT BY 1;

-- 4. CREW_JOIN_REQUEST TABLE
CREATE TABLE CREW_JOIN_REQUEST
(
    CREW_JOIN_REQUEST_ID NUMBER PRIMARY KEY,
    CREW_ID              NUMBER REFERENCES CREW (CREW_ID),
    MEMBER_ID            NUMBER REFERENCES MEMBER (MEMBER_ID),
    STATUS               VARCHAR2(50) DEFAULT 'REQUEST' CHECK ( STATUS IN ('REQUEST', 'ACCEPT', 'DENY') ),
    REQUEST_MESSAGE      VARCHAR2(1000),
    CREATED_AT           TIMESTAMP    DEFAULT SYSDATE,
    CREATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT           TIMESTAMP,
    UPDATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW_JOIN_REQUEST START WITH 1 INCREMENT BY 1;

-- 5. ANNOUNCEMENT TABLE
CREATE TABLE ANNOUNCEMENT
(
    ANNOUNCEMENT_ID   NUMBER PRIMARY KEY,
    ANNOUNCEMENT_TYPE VARCHAR2(50) DEFAULT 'CREW' CHECK ( ANNOUNCEMENT_TYPE IN ('ALL', 'CREW') ),
    TITLE             VARCHAR2(255)  NOT NULL,
    CONTENT           VARCHAR2(2000) NOT NULL,
    WRITER            NUMBER REFERENCES MEMBER (MEMBER_ID),
    CREATED_AT        TIMESTAMP    DEFAULT SYSDATE,
    CREATED_BY        NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT        TIMESTAMP,
    UPDATED_BY        NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ANNOUNCEMENT START WITH 1 INCREMENT BY 1;

-- 6. FEED TABLE
CREATE TABLE FEED
(
    FEED_ID    NUMBER PRIMARY KEY,
    WRITER     NUMBER REFERENCES MEMBER (MEMBER_ID),
    CONTENT    VARCHAR2(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED START WITH 1 INCREMENT BY 1;

-- 7. FEED_COMMENT TABLE
CREATE TABLE FEED_COMMENT
(
    COMMENT_ID NUMBER PRIMARY KEY,
    FEED_ID    NUMBER REFERENCES FEED (FEED_ID),
    WRITER     NUMBER REFERENCES MEMBER (MEMBER_ID),
    CONTENT    VARCHAR2(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT TIMESTAMP,
    UPDATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_COMMENT START WITH 1 INCREMENT BY 1;

-- 8. FEED_LIKE TABLE
CREATE TABLE FEED_LIKE
(
    FEED_LIKE_ID NUMBER PRIMARY KEY,
    FEED_ID      NUMBER REFERENCES FEED (FEED_ID),
    MEMBER_ID    NUMBER REFERENCES MEMBER (MEMBER_ID),
    CREATED_AT   TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_LIKE START WITH 1 INCREMENT BY 1;

-- 9. FEED_FILE TABLE
CREATE TABLE FEED_FILE
(
    FEED_FILE_ID NUMBER PRIMARY KEY,
    FILE_URL     VARCHAR2(1000) NOT NULL,
    FEED_ID      NUMBER REFERENCES FEED (FEED_ID),
    CREATED_AT   TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_FILE START WITH 1 INCREMENT BY 1;

-- 10. ANNOUNCEMENT_FILE TABLE
CREATE TABLE ANNOUNCEMENT_FILE
(
    ANNOUNCEMENT_FILE_ID NUMBER PRIMARY KEY,
    FILE_URL             VARCHAR2(1000) NOT NULL,
    ANNOUNCEMENT_ID      NUMBER REFERENCES ANNOUNCEMENT (ANNOUNCEMENT_ID),
    CREATED_AT           TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT           TIMESTAMP,
    UPDATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ANNOUNCEMENT_FILE START WITH 1 INCREMENT BY 1;

-- 11. FOLLOW TABLE
CREATE TABLE FOLLOW
(
    FOLLOW_ID   NUMBER PRIMARY KEY,
    FOLLOWER_ID NUMBER REFERENCES MEMBER (MEMBER_ID),
    FOLLOWED_ID NUMBER REFERENCES MEMBER (MEMBER_ID),
    CREATED_AT  TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY  NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT  TIMESTAMP,
    UPDATED_BY  NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FOLLOW START WITH 1 INCREMENT BY 1;

-- 12. ACTIVITY_LOG TABLE
CREATE TABLE ACTIVITY_LOG
(
    ACTIVITY_ID  NUMBER PRIMARY KEY,
    ACTION_TYPE  VARCHAR2(100) CHECK ( ACTION_TYPE IN
                                       ('MEMBER', 'CREW', 'CREW_MEMBER', 'CREW_JOIN_REQUEST', 'ANNOUNCEMENT',
                                        'FEED', 'FEED_COMMENT', 'FEED_LIKE', 'FEED_FILE',
                                        'ANNOUNCEMENT_FILE', 'FOLLOW')),
    REFERENCE_ID NUMBER,
    CREATED_AT   TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ACTIVITY_LOG START WITH 1 INCREMENT BY 1;

-- 13. URL_CLICK_LOG TABLE
CREATE TABLE URL_CLICK_LOG
(
    CLICK_LOG_ID NUMBER PRIMARY KEY,
    MEMBER_ID    NUMBER REFERENCES MEMBER (MEMBER_ID),
    IP           VARCHAR2(100),
    URL          VARCHAR2(1000) NOT NULL,
    CLICKED_AT   TIMESTAMP,
    CREATED_AT   TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_URL_CLICK_LOG START WITH 1 INCREMENT BY 1;

-- 14. STATISTIC TABLE
CREATE TABLE STATISTIC
(
    STATISTIC_ID NUMBER PRIMARY KEY
);
CREATE SEQUENCE SEQ_STATISTIC START WITH 1 INCREMENT BY 1;
