-- ---------------------------------------- member ----------------------------------------
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user1@example.com', '러너스하이', '010-0000-0001', 'hashed_pwd_1', 'USER',
        '/profile/metamong.jpeg',
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user2@example.com', '하치와레', '010-0000-0002', 'hashed_pwd_2', 'USER',
        '/profile/metamong.jpeg',
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user3@example.com', '정하영', '010-0000-0003', 'hashed_pwd_3', 'USER',
        '/profile/80cbb692-c522-4930-b65d-94c78173e789_profile.png',
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user4@example.com', '이수진', '010-0000-0004', 'hashed_pwd_4', 'USER',
        '/profile/b155e12c-b32f-4e32-bcd2-7cffbeceee8c_profile.png',
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user5@example.com', '신은혜', '010-0000-0005', 'hashed_pwd_5', 'USER',
        '/profile/hachiwarae.png',
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user6@example.com', '박준현', '010-0000-0006', 'hashed_pwd_1', 'ADMIN',
        null,
        TO_TIMESTAMP('2025-06-06 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user7@example.com', '정재영', '010-0000-0007', 'hashed_pwd_6', 'USER',
        null,
        TO_TIMESTAMP('2025-06-10 13:15:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER (MEMBER_ID, EMAIL, NICKNAME, PHONE, PWD_HASH, ROLE, PROFILE_PATH, CREATED_AT)
VALUES (SEQ_MEMBER.NEXTVAL, 'user8@example.com', '김아영', '010-0000-0008', 'hashed_pwd_8', 'COMPANY',
        null,
        TO_TIMESTAMP('2025-06-10 13:16:17', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- crew ----------------------------------------
INSERT INTO CREW (CREW_ID, CREW_NAME, CREW_ADDRESS, CREW_REGION, INTRODUCE, PROFILE_PATH, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW.NEXTVAL, 'Crew 1', 'Address 1', 'Region 1', 'Intro 1', '/profile/crew1.jpg', 1,
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW (CREW_ID, CREW_NAME, CREW_ADDRESS, CREW_REGION, INTRODUCE, PROFILE_PATH, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW.NEXTVAL, 'Crew 2', 'Address 2', 'Region 2', 'Intro 2', '/profile/crew2.jpg', 2,
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW (CREW_ID, CREW_NAME, CREW_ADDRESS, CREW_REGION, INTRODUCE, PROFILE_PATH, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW.NEXTVAL, 'Crew 3', 'Address 3', 'Region 3', 'Intro 3', '/profile/crew3.jpg', 3,
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW (CREW_ID, CREW_NAME, CREW_ADDRESS, CREW_REGION, INTRODUCE, PROFILE_PATH, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW.NEXTVAL, 'Crew 4', 'Address 4', 'Region 4', 'Intro 4', '/profile/crew4.jpg', 4,
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW (CREW_ID, CREW_NAME, CREW_ADDRESS, CREW_REGION, INTRODUCE, PROFILE_PATH, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW.NEXTVAL, 'Crew 5', 'Address 5', 'Region 5', 'Intro 5', '/profile/crew5.jpg', 5,
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- crew member ----------------------------------------
INSERT INTO CREW_MEMBER (CREW_MEMBER_ID, MEMBER_ID, CREW_ID, IS_LEADER, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW_MEMBER.NEXTVAL, 1, 1, 'N', 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW_MEMBER (CREW_MEMBER_ID, MEMBER_ID, CREW_ID, IS_LEADER, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW_MEMBER.NEXTVAL, 2, 2, 'N', 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW_MEMBER (CREW_MEMBER_ID, MEMBER_ID, CREW_ID, IS_LEADER, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW_MEMBER.NEXTVAL, 3, 3, 'N', 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW_MEMBER (CREW_MEMBER_ID, MEMBER_ID, CREW_ID, IS_LEADER, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW_MEMBER.NEXTVAL, 4, 4, 'N', 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREW_MEMBER (CREW_MEMBER_ID, MEMBER_ID, CREW_ID, IS_LEADER, CREATED_BY, CREATED_AT)
VALUES (SEQ_CREW_MEMBER.NEXTVAL, 5, 5, 'N', 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- feed ----------------------------------------
INSERT INTO FEED (FEED_ID, CONTENT, VIEW_COUNT, LAT, LNG, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED.NEXTVAL, 'Feed content 1', 39, 37.51, 127.01, 1,
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED (FEED_ID, CONTENT, VIEW_COUNT, LAT, LNG, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED.NEXTVAL, 'Feed content 2', 21, 37.52, 127.02, 2,
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED (FEED_ID, CONTENT, VIEW_COUNT, LAT, LNG, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED.NEXTVAL, 'Feed content 3', 8, 37.53, 127.03, 3,
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED (FEED_ID, CONTENT, VIEW_COUNT, LAT, LNG, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED.NEXTVAL, 'Feed content 4', 4, 37.54, 127.04, 4,
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED (FEED_ID, CONTENT, VIEW_COUNT, LAT, LNG, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED.NEXTVAL, 'Feed content 5', 73, 37.55, 127.05, 5,
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- feed url ----------------------------------------
INSERT INTO FEED_URL (FEED_URL_ID, FEED_ID, URL)
VALUES (SEQ_FEED_URL.NEXTVAL, 1, 'https://example.com/feed1');
INSERT INTO FEED_URL (FEED_URL_ID, FEED_ID, URL)
VALUES (SEQ_FEED_URL.NEXTVAL, 2, 'https://example.com/feed2');
INSERT INTO FEED_URL (FEED_URL_ID, FEED_ID, URL)
VALUES (SEQ_FEED_URL.NEXTVAL, 3, 'https://example.com/feed3');
INSERT INTO FEED_URL (FEED_URL_ID, FEED_ID, URL)
VALUES (SEQ_FEED_URL.NEXTVAL, 4, 'https://example.com/feed4');
INSERT INTO FEED_URL (FEED_URL_ID, FEED_ID, URL)
VALUES (SEQ_FEED_URL.NEXTVAL, 5, 'https://example.com/feed5');
-- ---------------------------------------- member wallet ----------------------------------------
INSERT INTO MEMBER_WALLET (MEMBER_WALLET_ID, FEED_ID, MEMBER_ID, CHARGE_AMOUNT, BALANCE, CREATED_BY, CREATED_AT)
VALUES (SEQ_MEMBER_WALLET.NEXTVAL, 1, 1, 1000, 4000, 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER_WALLET (MEMBER_WALLET_ID, FEED_ID, MEMBER_ID, CHARGE_AMOUNT, BALANCE, CREATED_BY, CREATED_AT)
VALUES (SEQ_MEMBER_WALLET.NEXTVAL, 2, 2, 2000, 3000, 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER_WALLET (MEMBER_WALLET_ID, FEED_ID, MEMBER_ID, CHARGE_AMOUNT, BALANCE, CREATED_BY, CREATED_AT)
VALUES (SEQ_MEMBER_WALLET.NEXTVAL, 3, 3, 3000, 2000, 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER_WALLET (MEMBER_WALLET_ID, FEED_ID, MEMBER_ID, CHARGE_AMOUNT, BALANCE, CREATED_BY, CREATED_AT)
VALUES (SEQ_MEMBER_WALLET.NEXTVAL, 4, 4, 4000, 1000, 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MEMBER_WALLET (MEMBER_WALLET_ID, FEED_ID, MEMBER_ID, CHARGE_AMOUNT, BALANCE, CREATED_BY, CREATED_AT)
VALUES (SEQ_MEMBER_WALLET.NEXTVAL, 5, 5, 5000, 0, 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- feed comment ----------------------------------------
INSERT INTO FEED_COMMENT (COMMENT_ID, FEED_ID, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_COMMENT.NEXTVAL, 1, 'Comment 1', 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_COMMENT (COMMENT_ID, FEED_ID, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_COMMENT.NEXTVAL, 2, 'Comment 2', 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_COMMENT (COMMENT_ID, FEED_ID, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_COMMENT.NEXTVAL, 3, 'Comment 3', 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_COMMENT (COMMENT_ID, FEED_ID, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_COMMENT.NEXTVAL, 4, 'Comment 4', 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_COMMENT (COMMENT_ID, FEED_ID, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_COMMENT.NEXTVAL, 5, 'Comment 5', 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- feed like ----------------------------------------
INSERT INTO FEED_LIKE (FEED_LIKE_ID, FEED_ID, MEMBER_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_LIKE.NEXTVAL, 1, 1, 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_LIKE (FEED_LIKE_ID, FEED_ID, MEMBER_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_LIKE.NEXTVAL, 2, 1, 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_LIKE (FEED_LIKE_ID, FEED_ID, MEMBER_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_LIKE.NEXTVAL, 3, 2, 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_LIKE (FEED_LIKE_ID, FEED_ID, MEMBER_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_LIKE.NEXTVAL, 4, 1, 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_LIKE (FEED_LIKE_ID, FEED_ID, MEMBER_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_LIKE.NEXTVAL, 5, 2, 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- feed file ----------------------------------------
INSERT INTO FEED_FILE (FEED_FILE_ID, FILE_PATH, FILE_ORDER, FEED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_FILE.NEXTVAL, 'release/feed/1/128a65cf-a364-4a84-bc47-59dd4f435d96_metamong.jpeg', 1, 1, 1,
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_FILE (FEED_FILE_ID, FILE_PATH, FILE_ORDER, FEED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_FILE.NEXTVAL, 'release/feed/2/runner_img.webp', 1, 2, 2,
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_FILE (FEED_FILE_ID, FILE_PATH, FILE_ORDER, FEED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_FILE.NEXTVAL, 'release/feed/3/runner_img.webp', 1, 3, 3,
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_FILE (FEED_FILE_ID, FILE_PATH, FILE_ORDER, FEED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_FILE.NEXTVAL, 'release/feed/4/runner_img.webp', 1, 4, 4,
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FEED_FILE (FEED_FILE_ID, FILE_PATH, FILE_ORDER, FEED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FEED_FILE.NEXTVAL, 'release/feed/5/runner_img.webp', 1, 5, 5,
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- announcement ----------------------------------------
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_ID, ANNOUNCEMENT_TYPE, TITLE, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 'CREW', 'Title 1', 'Announcement content 1', 1,
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_ID, ANNOUNCEMENT_TYPE, TITLE, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 'CREW', 'Title 2', 'Announcement content 2', 2,
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_ID, ANNOUNCEMENT_TYPE, TITLE, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 'CREW', 'Title 3', 'Announcement content 3', 3,
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_ID, ANNOUNCEMENT_TYPE, TITLE, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 'CREW', 'Title 4', 'Announcement content 4', 4,
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_ID, ANNOUNCEMENT_TYPE, TITLE, CONTENT, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 'CREW', 'Title 5', 'Announcement content 5', 5,
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- announcement file ----------------------------------------
INSERT INTO ANNOUNCEMENT_FILE (ANNOUNCEMENT_FILE_ID, FILE_PATH, ANNOUNCEMENT_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT_FILE.NEXTVAL, '/files/announcement1.pdf', 1, 1,
        TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT_FILE (ANNOUNCEMENT_FILE_ID, FILE_PATH, ANNOUNCEMENT_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT_FILE.NEXTVAL, '/files/announcement2.pdf', 2, 2,
        TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT_FILE (ANNOUNCEMENT_FILE_ID, FILE_PATH, ANNOUNCEMENT_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT_FILE.NEXTVAL, '/files/announcement3.pdf', 3, 3,
        TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT_FILE (ANNOUNCEMENT_FILE_ID, FILE_PATH, ANNOUNCEMENT_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT_FILE.NEXTVAL, '/files/announcement4.pdf', 4, 4,
        TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ANNOUNCEMENT_FILE (ANNOUNCEMENT_FILE_ID, FILE_PATH, ANNOUNCEMENT_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ANNOUNCEMENT_FILE.NEXTVAL, '/files/announcement5.pdf', 5, 5,
        TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- follow ----------------------------------------
INSERT INTO FOLLOW (FOLLOW_ID, FOLLOWED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FOLLOW.NEXTVAL, 5, 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FOLLOW (FOLLOW_ID, FOLLOWED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FOLLOW.NEXTVAL, 4, 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FOLLOW (FOLLOW_ID, FOLLOWED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FOLLOW.NEXTVAL, 3, 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FOLLOW (FOLLOW_ID, FOLLOWED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FOLLOW.NEXTVAL, 2, 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO FOLLOW (FOLLOW_ID, FOLLOWED_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_FOLLOW.NEXTVAL, 1, 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- activity log ----------------------------------------
INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED', 'POST', 1, 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED', 'POST', 2, 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED', 'POST', 3, 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED', 'POST', 4, 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_BY, CREATED_AT)
VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED', 'POST', 5, 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
-- ---------------------------------------- url click log ----------------------------------------
INSERT INTO URL_CLICK_LOG (URL_CLICK_LOG_ID, FEED_URL_ID, IP, CREATED_BY, CREATED_AT)
VALUES (SEQ_URL_CLICK_LOG.NEXTVAL, 1, '192.168.0.1', 1, TO_TIMESTAMP('2025-06-04 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO URL_CLICK_LOG (URL_CLICK_LOG_ID, FEED_URL_ID, IP, CREATED_BY, CREATED_AT)
VALUES (SEQ_URL_CLICK_LOG.NEXTVAL, 2, '192.168.0.2', 2, TO_TIMESTAMP('2025-06-03 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO URL_CLICK_LOG (URL_CLICK_LOG_ID, FEED_URL_ID, IP, CREATED_BY, CREATED_AT)
VALUES (SEQ_URL_CLICK_LOG.NEXTVAL, 3, '192.168.0.3', 3, TO_TIMESTAMP('2025-06-02 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO URL_CLICK_LOG (URL_CLICK_LOG_ID, FEED_URL_ID, IP, CREATED_BY, CREATED_AT)
VALUES (SEQ_URL_CLICK_LOG.NEXTVAL, 4, '192.168.0.4', 4, TO_TIMESTAMP('2025-06-01 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO URL_CLICK_LOG (URL_CLICK_LOG_ID, FEED_URL_ID, IP, CREATED_BY, CREATED_AT)
VALUES (SEQ_URL_CLICK_LOG.NEXTVAL, 5, '192.168.0.5', 5, TO_TIMESTAMP('2025-06-05 16:28:03', 'YYYY-MM-DD HH24:MI:SS'));

COMMIT;