server:
  port: 8080

logging:
  level:
    root: INFO

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.hyundae_futurenet.rocketddan.runners_hi.backend.model

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info  # 또는 '*' 로 전체 노출
  endpoint:
    health:
      show-details: always

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

s3:
  upload_path:
    member_profile: release/member-profile/
    crew_profile: release/crew-profile/
    feed: release/feed/
    announcement: release/announcement/
  upload_bucket:
    name: "runners-hi-bucket"

cloudfront:
  distribution-domain: d3j62hm9xnqci3.cloudfront.net
  key-pair-id: K1CXY699RY3FDX
  private-key-path: ${CLOUDFRONT_PRIVATE_KEY_PATH}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: backend

  #  data:
  #    redis:
  #      host: ${REDIS_HOST}
  #      port: 6379

  datasource:
    url: jdbc:oracle:thin:@${ORACLE_DB_CONNECTION_NAME}?TNS_ADMIN=${ORACLE_WALLET_DIRECTORY_PATH}
    username: ${ORACLE_DB_USER_NAME}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: "ALTER SESSION SET TIME_ZONE = 'Asia/Seoul'"
      maximum-pool-size: 20
      minimum-idle: 3
      idle-timeout: 300000  # 5분
      max-lifetime: 900000  # 15분 (autonomous db는 session recycling 주기가 있기 때문에 너무 길게 안잡음)
      validation-timeout: 5000
      connection-timeout: 30000

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${SERVER_DOMAIN}/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}
  signup-token-expiration-minutes: ${SIGNUP_TOKEN_EXPIRATION_MINUTES}

app:
  client-domain: ${CLIENT_DOMAIN}
  server-domain: ${SERVER_DOMAIN}
