server:
  port: 8080

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  application:
    name: backend

  datasource:
    url: jdbc:oracle:thin:@${ORACLE_DB_CONNECTION_NAME}?TNS_ADMIN=${ORACLE_WALLET_DIRECTORY_PATH}
    username: ${ORACLE_DB_USER_NAME}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver