-- 1. MEMBER TABLE
CREATE TABLE MEMBER
(
    MEMBER_ID    NUMBER PRIMARY KEY,
    EMAIL        VARCHAR2(255) NOT NULL,
    NICKNAME     VARCHAR2(255) NOT NULL,
    PHONE        VARCHAR2(20)  NOT NULL,
    PWD_HASH     VARCHAR2(255) NOT NULL,
    ROLE         VARCHAR2(50) DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN', 'COMPANY') ),
    PROFILE_PATH VARCHAR2(500),
    CREATED_AT   TIMESTAMP WITH TIME ZONE
                              DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    UPDATED_AT   TIMESTAMP WITH TIME ZONE,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    DELETED_AT   TIMESTAMP WITH TIME ZONE,
    DELETED_BY   NUMBER
);
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1;

-- 2. CREW TABLE
CREATE TABLE CREW
(
    CREW_ID      NUMBER PRIMARY KEY,
    CREW_NAME    VARCHAR2(255) NOT NULL,
    CREW_ADDRESS VARCHAR2(255) NOT NULL,
    CREW_REGION  VARCHAR2(100) NOT NULL,
    INTRODUCE    VARCHAR2(1000),
    PROFILE_PATH VARCHAR2(500),
    CREATED_AT   TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP WITH TIME ZONE,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW START WITH 1 INCREMENT BY 1;

-- 3. CREW_MEMBER TABLE
CREATE TABLE CREW_MEMBER
(
    CREW_MEMBER_ID NUMBER PRIMARY KEY,
    MEMBER_ID      NUMBER REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CREW_ID        NUMBER REFERENCES CREW (CREW_ID) ON DELETE CASCADE,
    IS_LEADER      CHAR(1) DEFAULT 'N' CHECK ( IS_LEADER IN ('Y', 'N') ),
    CREATED_AT     TIMESTAMP WITH TIME ZONE
                           DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY     NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT     TIMESTAMP WITH TIME ZONE,
    UPDATED_BY     NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW_MEMBER START WITH 1 INCREMENT BY 1;

-- 4. CREW_JOIN_REQUEST TABLE
CREATE TABLE CREW_JOIN_REQUEST
(
    CREW_JOIN_REQUEST_ID NUMBER PRIMARY KEY,
    CREW_ID              NUMBER REFERENCES CREW (CREW_ID),
    MEMBER_ID            NUMBER REFERENCES MEMBER (MEMBER_ID),
    STATUS               VARCHAR2(50) DEFAULT 'REQUEST' CHECK ( STATUS IN ('REQUEST', 'ACCEPT', 'DENY') ),
    REQUEST_MESSAGE      VARCHAR2(1000),
    CREATED_AT           TIMESTAMP WITH TIME ZONE
                                      DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT           TIMESTAMP WITH TIME ZONE,
    UPDATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_CREW_JOIN_REQUEST START WITH 1 INCREMENT BY 1;

-- 5. ANNOUNCEMENT TABLE
CREATE TABLE ANNOUNCEMENT
(
    ANNOUNCEMENT_ID   NUMBER PRIMARY KEY,
    ANNOUNCEMENT_TYPE VARCHAR2(50) DEFAULT 'CREW' CHECK ( ANNOUNCEMENT_TYPE IN ('ALL', 'CREW') ),
    TITLE             VARCHAR2(255)  NOT NULL,
    CONTENT           VARCHAR2(2000) NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE
                                   DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY        NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT        TIMESTAMP WITH TIME ZONE,
    UPDATED_BY        NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ANNOUNCEMENT START WITH 1 INCREMENT BY 1;

-- 6. FEED TABLE
CREATE TABLE FEED
(
    FEED_ID    NUMBER PRIMARY KEY,
    CONTENT    VARCHAR2(2000) NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    LAT        NUMBER,
    LNG        NUMBER,
    CREATED_AT TIMESTAMP WITH TIME ZONE
                      DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED START WITH 1 INCREMENT BY 1;

-- 7. MEMBER_WALLET TABLE
CREATE TABLE MEMBER_WALLET
(
    MEMBER_WALLET_ID NUMBER PRIMARY KEY,
    FEED_ID          NUMBER REFERENCES FEED (FEED_ID),
    MEMBER_ID        NUMBER REFERENCES MEMBER (MEMBER_ID),
    CHARGE_AMOUNT    NUMBER DEFAULT 0,
    BALANCE          NUMBER DEFAULT 0,
    CREATED_AT       TIMESTAMP WITH TIME ZONE
                            DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY       NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT       TIMESTAMP WITH TIME ZONE,
    UPDATED_BY       NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_MEMBER_WALLET START WITH 1 INCREMENT BY 1;

-- 8. FEED_URL TABLE
CREATE TABLE FEED_URL
(
    FEED_URL_ID NUMBER PRIMARY KEY,
    FEED_ID     NUMBER REFERENCES FEED (FEED_ID),
    URL         VARCHAR2(1000) NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY  NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT  TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_URL START WITH 1 INCREMENT BY 1;

-- 9. FEED_COMMENT TABLE
CREATE TABLE FEED_COMMENT
(
    COMMENT_ID NUMBER PRIMARY KEY,
    FEED_ID    NUMBER REFERENCES FEED (FEED_ID),
    CONTENT    VARCHAR2(1000) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_BY NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_COMMENT START WITH 1 INCREMENT BY 1;

-- 10. FEED_LIKE TABLE
CREATE TABLE FEED_LIKE
(
    FEED_LIKE_ID NUMBER PRIMARY KEY,
    FEED_ID      NUMBER REFERENCES FEED (FEED_ID),
    CREATED_AT   TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_LIKE START WITH 1 INCREMENT BY 1;

-- 11. FEED_FILE TABLE
CREATE TABLE FEED_FILE
(
    FEED_FILE_ID NUMBER PRIMARY KEY,
    FILE_PATH    VARCHAR2(1000) NOT NULL,
    FEED_ID      NUMBER REFERENCES FEED (FEED_ID),
    CREATED_AT   TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT   TIMESTAMP WITH TIME ZONE,
    UPDATED_BY   NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FEED_FILE START WITH 1 INCREMENT BY 1;

-- 12. ANNOUNCEMENT_FILE TABLE
CREATE TABLE ANNOUNCEMENT_FILE
(
    ANNOUNCEMENT_FILE_ID NUMBER PRIMARY KEY,
    FILE_PATH            VARCHAR2(1000) NOT NULL,
    ANNOUNCEMENT_ID      NUMBER REFERENCES ANNOUNCEMENT (ANNOUNCEMENT_ID),
    CREATED_AT           TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID),
    UPDATED_AT           TIMESTAMP WITH TIME ZONE,
    UPDATED_BY           NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ANNOUNCEMENT_FILE START WITH 1 INCREMENT BY 1;

-- 13. FOLLOW TABLE
CREATE TABLE FOLLOW
(
    FOLLOW_ID   NUMBER PRIMARY KEY,
    FOLLOWED_ID NUMBER REFERENCES MEMBER (MEMBER_ID),
    CREATED_AT  TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY  NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_FOLLOW START WITH 1 INCREMENT BY 1;


-- 14. URL_CLICK_LOG TABLE
CREATE TABLE URL_CLICK_LOG
(
    URL_CLICK_LOG_ID NUMBER PRIMARY KEY,
    FEED_URL_ID      NUMBER REFERENCES FEED_URL (FEED_URL_ID),
    IP               VARCHAR2(100),
    CREATED_AT       TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY       NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_URL_CLICK_LOG START WITH 1 INCREMENT BY 1;

-- 15. ACTIVITY_LOG TABLE
CREATE TABLE ACTIVITY_LOG
(
    ACTIVITY_LOG_ID   NUMBER PRIMARY KEY,
    TARGET_TABLE_NAME VARCHAR2(50) CHECK ( TARGET_TABLE_NAME IN
                                           ('MEMBER', 'CREW', 'CREW_MEMBER', 'CREW_JOIN_REQUEST', 'ANNOUNCEMENT',
                                            'FEED', 'FEED_URL', 'FEED_COMMENT', 'FEED_LIKE', 'FEED_FILE',
                                            'ANNOUNCEMENT_FILE', 'FOLLOW', 'URL_CLICK_LOG')),
    ACTION            VARCHAR2(100) CHECK ( ACTION IN
                                            ('POST', 'UPDATE', 'DELETE')),
    REFERENCE_ID      NUMBER,
    CREATED_AT        TIMESTAMP WITH TIME ZONE
        DEFAULT (SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul'),
    CREATED_BY        NUMBER REFERENCES MEMBER (MEMBER_ID)
);
CREATE SEQUENCE SEQ_ACTIVITY_LOG START WITH 1 INCREMENT BY 1;
