----------------------------------------------------
-- 10. FEED_LIKE
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FEED_LIKE_INSERT
    AFTER INSERT
    ON FEED_LIKE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_LIKE', 'POST', :NEW.FEED_LIKE_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_LIKE_UPDATE
    AFTER UPDATE
    ON FEED_LIKE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_LIKE', 'UPDATE', :NEW.FEED_LIKE_ID, SYSDATE,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_LIKE_DELETE
    AFTER DELETE
    ON FEED_LIKE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_LIKE', 'DELETE', :OLD.FEED_LIKE_ID, SYSDATE,
            :OLD.CREATED_BY);
END;
/