----------------------------------------------------
-- 11. FEED_FILE
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FEED_FILE_INSERT
    AFTER INSERT
    ON FEED_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_FILE', 'POST', :NEW.FEED_FILE_ID, SYSTIMESTAMP, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_FILE_UPDATE
    AFTER UPDATE
    ON FEED_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_FILE', 'UPDATE', :NEW.FEED_FILE_ID, SYSTIMESTAMP,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_FILE_DELETE
    AFTER DELETE
    ON FEED_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_FILE', 'DELETE', :OLD.FEED_FILE_ID, SYSTIMESTAMP,
            :OLD.CREATED_BY);
END;
/