----------------------------------------------------
-- 12. ANNOUNCEMENT_FILE
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_FILE_INSERT
    AFTER INSERT
    ON ANNOUNCEMENT_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT_FILE', 'POST', :NEW.ANNOUNCEMENT_FILE_ID, SYSTIMESTAMP,
            :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_FILE_UPDATE
    AFTER UPDATE
    ON ANNOUNCEMENT_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT_FILE', 'UPDATE', :NEW.ANNOUNCEMENT_FILE_ID, SYSTIMESTAMP,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_FILE_DELETE
    AFTER DELETE
    ON ANNOUNCEMENT_FILE
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT_FILE', 'DELETE', :OLD.ANNOUNCEMENT_FILE_ID, SYSTIMESTAMP,
            :OLD.CREATED_BY);
END;
/