----------------------------------------------------
-- 13. FOLLOW
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FOLLOW_INSERT
    AFTER INSERT
    ON FOLLOW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FOLLOW', 'POST', :NEW.FOLLOW_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FOLLOW_UPDATE
    AFTER UPDATE
    ON FOLLOW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FOLLOW', 'UPDATE', :NEW.FOLLOW_ID, SYSDATE,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FOLLOW_DELETE
    AFTER DELETE
    ON FOLLOW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FOLLOW', 'DELETE', :OLD.FOLLOW_ID, SYSDATE,
            :OLD.CREATED_BY);
END;
/