----------------------------------------------------
-- 14. URL_CLICK_LOG
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_URL_CLICK_LOG_INSERT
    AFTER INSERT
    ON URL_CLICK_LOG
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'URL_CLICK_LOG', 'POST', :NEW.URL_CLICK_LOG_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_URL_CLICK_LOG_UPDATE
    AFTER UPDATE
    ON URL_CLICK_LOG
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'URL_CLICK_LOG', 'UPDATE', :NEW.URL_CLICK_LOG_ID, SYSDATE,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_URL_CLICK_LOG_DELETE
    AFTER DELETE
    ON URL_CLICK_LOG
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'URL_CLICK_LOG', 'DELETE', :OLD.URL_CLICK_LOG_ID, SYSDATE,
            :OLD.CREATED_BY);
END;
/