----------------------------------------------------
-- 1. MEMBER
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MEMBER_INSERT
    AFTER INSERT
    ON MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER', 'POST', :NEW.MEMBER_ID, SYSDATE, :NEW.MEMBER_ID);
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBER_UPDATE
    AFTER UPDATE
    ON MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER', 'UPDATE', :NEW.MEMBER_ID, SYSDATE, :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBER_DELETE
    AFTER DELETE
    ON MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER', 'DELETE', :OLD.MEMBER_ID, SYSDATE, :OLD.MEMBER_ID);
END;
/