----------------------------------------------------
-- 2. CREW
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CREW_INSERT
    AFTER INSERT
    ON CREW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW', 'POST', :NEW.CREW_ID, SYSTIMESTAMP, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_UPDATE
    AFTER UPDATE
    ON CREW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW', 'UPDATE', :NEW.CREW_ID, SYSTIMESTAMP, :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_DELETE
    AFTER DELETE
    ON CREW
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW', 'DELETE', :OLD.CREW_ID, SYSTIMESTAMP, :OLD.CREATED_BY);
END;
/