----------------------------------------------------
-- 3. CREW_MEMBER
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CREW_MEMBER_INSERT
    AFTER INSERT
    ON CREW_MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_MEMBER', 'POST', :NEW.CREW_MEMBER_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_MEMBER_UPDATE
    AFTER UPDATE
    ON CREW_MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_MEMBER', 'UPDATE', :NEW.CREW_MEMBER_ID, SYSDATE, :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_MEMBER_DELETE
    AFTER DELETE
    ON CREW_MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_MEMBER', 'DELETE', :OLD.CREW_MEMBER_ID, SYSDATE, :OLD.CREATED_BY);
END;
/