----------------------------------------------------
-- 4. CREW_JOIN_REQUEST
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CREW_JOIN_REQUEST_INSERT
    AFTER INSERT
    ON CREW_JOIN_REQUEST
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_JOIN_REQUEST', 'POST', :NEW.CREW_JOIN_REQUEST_ID, SYSTIMESTAMP, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_JOIN_REQUEST_UPDATE
    AFTER UPDATE
    ON CREW_JOIN_REQUEST
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_JOIN_REQUEST', 'UPDATE', :NEW.CREW_JOIN_REQUEST_ID, SYSTIMESTAMP,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_CREW_JOIN_REQUEST_DELETE
    AFTER DELETE
    ON CREW_JOIN_REQUEST
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'CREW_JOIN_REQUEST', 'DELETE', :OLD.CREW_JOIN_REQUEST_ID, SYSTIMESTAMP,
            :OLD.CREATED_BY);
END;
/