----------------------------------------------------
-- 5. ANNOUNCEMENT
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_INSERT
    AFTER INSERT
    ON ANNOUNCEMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT', 'POST', :NEW.ANNOUNCEMENT_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_UPDATE
    AFTER UPDATE
    ON ANNOUNCEMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT', 'UPDATE', :NEW.ANNOUNCEMENT_ID, SYSDATE,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENT_DELETE
    AFTER DELETE
    ON ANNOUNCEMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'ANNOUNCEMENT', 'DELETE', :OLD.ANNOUNCEMENT_ID, SYSDATE,
            :OLD.CREATED_BY);
END;
/