----------------------------------------------------
-- 7. MEMBER_WALLET
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MEMBER_WALLET_INSERT
    AFTER INSERT
    ON MEMBER_WALLET
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER_WALLET', 'POST', :NEW.MEMBER_WALLET_ID, SYSTIMESTAMP, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBER_WALLET_UPDATE
    AFTER UPDATE
    ON MEMBER_WALLET
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER_WALLET', 'UPDATE', :NEW.MEMBER_WALLET_ID, SYSTIMESTAMP,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_MEMBER_WALLET_DELETE
    AFTER DELETE
    ON MEMBER_WALLET
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'MEMBER_WALLET', 'DELETE', :OLD.MEMBER_WALLET_ID, SYSTIMESTAMP,
            :OLD.CREATED_BY);
END;
/