----------------------------------------------------
-- 8. FEED_URL
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FEED_URL_INSERT
    AFTER INSERT
    ON FEED_URL
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_URL', 'POST', :NEW.FEED_URL_ID, SYSTIMESTAMP, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_URL_UPDATE
    AFTER UPDATE
    ON FEED_URL
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_URL', 'UPDATE', :NEW.FEED_URL_ID, SYSTIMESTAMP,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_URL_DELETE
    AFTER DELETE
    ON FEED_URL
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_URL', 'DELETE', :OLD.FEED_URL_ID, SYSTIMESTAMP,
            :OLD.CREATED_BY);
END;
/