----------------------------------------------------
-- 9. FEED_COMMENT
----------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FEED_COMMENT_INSERT
    AFTER INSERT
    ON FEED_COMMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_COMMENT', 'POST', :NEW.COMMENT_ID, SYSDATE, :NEW.CREATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_COMMENT_UPDATE
    AFTER UPDATE
    ON FEED_COMMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_COMMENT', 'UPDATE', :NEW.COMMENT_ID, SYSDATE,
            :NEW.UPDATED_BY);
END;
/

CREATE OR REPLACE TRIGGER TRG_FEED_COMMENT_DELETE
    AFTER DELETE
    ON FEED_COMMENT
    FOR EACH ROW
BEGIN
    INSERT INTO ACTIVITY_LOG (ACTIVITY_LOG_ID, TARGET_TABLE_NAME, ACTION, REFERENCE_ID, CREATED_AT, CREATED_BY)
    VALUES (SEQ_ACTIVITY_LOG.NEXTVAL, 'FEED_COMMENT', 'DELETE', :OLD.COMMENT_ID, SYSDATE,
            :OLD.CREATED_BY);
END;
/